<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>spec</string>
	</array>
	<key>name</key>
	<string>Magma Spec</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\+\w+\b</string>
			<key>name</key>
			<string>keyword.control.include-spec.magma</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.magma.spec</string>
	<key>uuid</key>
	<string>96FFB456-8492-4ABB-BBB7-26AD55B15B4F</string>
</dict>
</plist>
